version: "3"
services:
    flask:
        build:
            context: .
            dockerfile: docker/Dockerfile.flask
        ports:
            - 8180:5000
        restart: always
        depends_on:
            - db
        volumes:
            - ./flaskapp:/app
        container_name: flask-server
        networks:
            - flask-network

    db:
        image: postgres:13.1-alpine
        container_name: flask-db
        environment:
            POSTGRES_USER: miya_db
            POSTGRES_PASSWORD: db
            #POSTGRES_DB: db
        #ports:
        #    - 5432:5432
        volumes:
            - ./storage/postgresql:/var/lib/postgresql/data
            - ./initdb:/docker-entrypoint-initdb.d
        networks:
            - flask-network

    test:
        build:
            context: .
            dockerfile: docker/Dockerfile.test
        depends_on:
            - flask
        volumes:
            - ./testapp:/app
        container_name: test-server
        networks:
            - flask-network

networks:
    flask-network:
        driver: bridge