version: "3"
services:
    flask:
        build:
            context: .
            dockerfile: docker/Dockerfile.flask
        ports:
            - 5000:5000
        depends_on:
            - db
        volumes:
            - ./flaskapp:/app
        container_name: flask-server
        networks:
            - starlette-network

    db:
        image: postgres:13.1-alpine
        container_name: flask-db
        environment:
            POSTGRES_USER: miya_db
            POSTGRES_PASSWORD: db
            #POSTGRES_DB: db
        ports:
            - 5432:5432
        volumes:
            - ./storage/postgresql:/var/lib/postgresql/data
            - ./initdb:/docker-entrypoint-initdb.d
        networks:
            - starlette-network

networks:
    starlette-network:
        driver: bridge