FROM python:3.7-slim
ENV PYTHONUNBUFFERED 1
RUN apt update
RUN mkdir /app
WORKDIR /app
COPY flaskapp/requirements.txt /app
RUN pip install -r requirements.txt
RUN mkdir /entry
COPY entry_flask.sh /entry
ENTRYPOINT ["/entry/entry_flask.sh"]